# Makefile

# One single executable

a.out : main.o Application_Test.o Bad_Aadhaar.o Bad_Booking.o Bad_Date.o Bad_Mobile.o Bad_Name.o Bad_Passenger.o Bad_Railways.o Bad_Station.o Concessions.o General_Concession.o Ladies_Concession.o SeniorCitizen_Concession.o Divyaang_Concession.o Date.o Station.o Name.o Gender.o Divyaang.o Passenger.o Railways.o BookingClass.o BookingCategory.o Booking.o
	g++ main.o Application_Test.o Bad_Aadhaar.o Bad_Booking.o Bad_Date.o Bad_Mobile.o Bad_Name.o Bad_Passenger.o Bad_Railways.o Bad_Station.o Concessions.o General_Concession.o Ladies_Concession.o SeniorCitizen_Concession.o Divyaang_Concession.o Date.o Station.o Name.o Gender.o Divyaang.o Passenger.o Railways.o BookingClass.o BookingCategory.o Booking.o -o a.out
	
main.o : main.cpp 
	g++ -c -std=c++17 -g -O0 -Wall main.cpp
	
Application_Test.o : Application_Test.cpp 
	g++ -c -std=c++17 -g -O0 Application_Test.cpp

Bad_Aadhaar.o : Bad_Aadhaar.cpp Bad_Aadhaar.h
	g++ -c -std=c++17 -g -O0 -Wall Bad_Aadhaar.cpp
	
Bad_Booking.o : Bad_Booking.cpp Bad_Booking.h
	g++ -c -std=c++17 -g -O0 -Wall Bad_Booking.cpp

Bad_Date.o : Bad_Date.cpp Bad_Date.h
	g++ -c -std=c++17 -g -O0 -Wall Bad_Date.cpp
	
Bad_Mobile.o : Bad_Mobile.cpp Bad_Mobile.h
	g++ -c -std=c++17 -g -O0 -Wall Bad_Mobile.cpp
	
Bad_Name.o : Bad_Name.cpp Bad_Name.h
	g++ -c -std=c++17 -g -O0 -Wall Bad_Name.cpp

Bad_Passenger.o : Bad_Passenger.cpp Bad_Passenger.h
	g++ -c -std=c++17 -g -O0 -Wall Bad_Passenger.cpp
	
Bad_Railways.o : Bad_Railways.cpp Bad_Railways.h
	g++ -c -std=c++17 -g -O0 -Wall Bad_Railways.cpp
	
Bad_Station.o : Bad_Station.cpp Bad_Station.h
	g++ -c -std=c++17 -g -O0 -Wall Bad_Station.cpp

Concessions.o : Concessions.cpp Concessions.h
	g++ -c -std=c++17 -g -O0 -Wall Concessions.cpp
	
General_Concession.o : General_Concession.cpp General_Concession.h
	g++ -c -std=c++17 -g -O0 -Wall General_Concession.cpp
	
Ladies_Concession.o : Ladies_Concession.cpp Ladies_Concession.h
	g++ -c -std=c++17 -g -O0 -Wall Ladies_Concession.cpp
	
SeniorCitizen_Concession.o : SeniorCitizen_Concession.cpp SeniorCitizen_Concession.h
	g++ -c -std=c++17 -g -O0 -Wall SeniorCitizen_Concession.cpp
	
Divyaang_Concession.o : Divyaang_Concession.cpp Divyaang_Concession.h
	g++ -c -std=c++17 -g -O0 -Wall Divyaang_Concession.cpp

Date.o : Date.cpp Date.h
	g++ -c -std=c++17 -g -O0 -Wall Date.cpp
	
Station.o : Station.cpp Station.h
	g++ -c -std=c++17 -g -O0 -Wall Station.cpp	

Name.o : Name.cpp Name.h 
	g++ -c -std=c++17 -g -O0 -Wall Name.cpp	
	
Gender.o : Gender.cpp Gender.h 
	g++ -c -std=c++17 -g -O0 -Wall Gender.cpp	
	
Divyaang.o : Divyaang.cpp Divyaang.h 
	g++ -c -std=c++17 -g -O0 -Wall Divyaang.cpp	
	
Passenger.o : Passenger.cpp Passenger.h 
	g++ -c -std=c++17 -g -O0 -Wall Passenger.cpp	
	
Railways.o : Railways.cpp Railways.h
	g++ -c -std=c++17 -g -O0 -Wall Railways.cpp

BookingClass.o : BookingClass.cpp BookingClass.h
	g++ -c -std=c++17 -g -O0 -Wall BookingClass.cpp
	
BookingCategory.o : BookingCategory.cpp BookingCategory.h
	g++ -c -std=c++17 -g -O0 -Wall BookingCategory.cpp
	
Booking.o : Booking.cpp Booking.h
	g++ -c -std=c++17 -g -O0 -Wall Booking.cpp
